stages:
  - build

include:
  - component: $CI_SERVER_FQDN/components/code-quality-oss/codequality-os-scanners-integration/golangci@1.0.1

build-image:
  image: podman
  stage: build
  before_script:
    - if [ ! -z "${DOCKER_REGISTRY_USER}" ] && [ ! -z "${DOCKER_REGISTRY_PASSWORD}" ] ;
      then
        echo "${DOCKER_REGISTRY_PASSWORD}" | docker login -u ${DOCKER_REGISTRY_USER} --password-stdin ${DOCKER_REGISTRY} ;
      fi
  script:
    # Build container
    - echo "Building ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
    - podman build -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} -f Containerfile .
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
